#!/usr/bin/env bash
# qbtc-testnet.sh — Launch and manage a QuantumBTC testnet node
#
# Usage:
#   ./contrib/qbtc-testnet/qbtc-testnet.sh start     # start testnet node in background
#   ./contrib/qbtc-testnet/qbtc-testnet.sh stop      # graceful shutdown
#   ./contrib/qbtc-testnet/qbtc-testnet.sh status    # show chain and DAG status
#   ./contrib/qbtc-testnet/qbtc-testnet.sh mine [N]  # mine N blocks (default: 1)
#   ./contrib/qbtc-testnet/qbtc-testnet.sh cli ...   # pass-through to bitcoin-cli
#   ./contrib/qbtc-testnet/qbtc-testnet.sh info      # getblockchaininfo
#   ./contrib/qbtc-testnet/qbtc-testnet.sh peers     # show connected peers
#   ./contrib/qbtc-testnet/qbtc-testnet.sh wallet    # create or load miner wallet
#   ./contrib/qbtc-testnet/qbtc-testnet.sh address   # get a new testnet address
#   ./contrib/qbtc-testnet/qbtc-testnet.sh send <addr> <amount>  # send QBTC
#   ./contrib/qbtc-testnet/qbtc-testnet.sh sweep <addr> [keep]   # drain wallet above reserve
#   ./contrib/qbtc-testnet/qbtc-testnet.sh autosweep <addr> [minutes] [keep]
#   ./contrib/qbtc-testnet/qbtc-testnet.sh throttle [pct]        # lower runtime CPU usage
#   ./contrib/qbtc-testnet/qbtc-testnet.sh repair-peers          # re-add bootstrap peers if connectivity is weak
#   ./contrib/qbtc-testnet/qbtc-testnet.sh doctor                # quick health check for sync and peers
#
# Environment:
#   QBTC_DATADIR   — custom data directory (default: ~/.bitcoin)
#   QBTC_BINDIR    — directory containing bitcoind/bitcoin-cli (default: ./src)
#   QBTC_WALLET    — wallet name for mining (default: miner)
#   QBTC_CONF      — custom config file path
#   QBTC_SEEDNODE  — extra seed node to connect to (ip:port)
#   QBTC_LOW_SPEC  — set to 1 for older or low-memory machines
#   QBTC_CPU_LIMIT — default CPU cap percent for throttle (default: 30)
#   QBTC_SWEEP_KEEP — reserve balance to keep when sweeping (default: 1.0)
#   QBTC_SWEEP_MAX  — max amount to send per sweep pass (default: 50)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

BINDIR="${QBTC_BINDIR:-${REPO_ROOT}/src}"
DATADIR="${QBTC_DATADIR:-$HOME/.bitcoin}"
WALLET="${QBTC_WALLET:-miner}"
CONF="${QBTC_CONF:-${DATADIR}/bitcoin.conf}"
SEEDNODE="${QBTC_SEEDNODE:-}"
LOW_SPEC="${QBTC_LOW_SPEC:-0}"
CPU_LIMIT_DEFAULT="${QBTC_CPU_LIMIT:-30}"
SWEEP_KEEP_DEFAULT="${QBTC_SWEEP_KEEP:-1.0}"
SWEEP_MAX_DEFAULT="${QBTC_SWEEP_MAX:-50}"
CHAIN="qbtctestnet"
BOOTSTRAP_PEERS=(
    "46.62.156.169:28333"
    "37.27.47.236:28333"
    "89.167.109.241:28333"
)

BITCOIND="${BINDIR}/bitcoind"
CLI="${BINDIR}/bitcoin-cli"

# Verify binaries exist
if [[ ! -x "$BITCOIND" ]]; then
    echo "ERROR: bitcoind not found at $BITCOIND"
    echo "Build first:  cd ${REPO_ROOT} && ./configure && make -j\$(nproc)"
    exit 1
fi
if [[ ! -x "$CLI" ]]; then
    echo "ERROR: bitcoin-cli not found at $CLI"
    exit 1
fi

# Build CLI args
CLI_ARGS=("-${CHAIN}")
DAEMON_ARGS=("-${CHAIN}" "-daemon")

if [[ -n "$DATADIR" ]]; then
    CLI_ARGS+=("-datadir=${DATADIR}")
    DAEMON_ARGS+=("-datadir=${DATADIR}")
fi

if [[ -n "$CONF" ]]; then
    CLI_ARGS+=("-conf=${CONF}")
    DAEMON_ARGS+=("-conf=${CONF}")
fi

if [[ -n "$SEEDNODE" ]]; then
    DAEMON_ARGS+=("-seednode=${SEEDNODE}")
fi

ensure_datadir() {
    mkdir -p "$DATADIR"
}

append_if_missing() {
    local line="$1"
    grep -Fqx "$line" "$CONF" 2>/dev/null || echo "$line" >> "$CONF"
}

ensure_config() {
    ensure_datadir

    if [[ ! -f "$CONF" ]]; then
        cat > "$CONF" <<EOF
# Auto-generated by qbtc-testnet.sh
chain=qbtctestnet

[qbtctestnet]
server=1
listen=1
discover=1
dnsseed=1
fallbackfee=0.0001
logtimestamps=1
maxconnections=$([[ "$LOW_SPEC" == "1" ]] && echo 16 || echo 32)
dbcache=$([[ "$LOW_SPEC" == "1" ]] && echo 128 || echo 512)
maxmempool=$([[ "$LOW_SPEC" == "1" ]] && echo 150 || echo 300)
maxsigcachesize=$([[ "$LOW_SPEC" == "1" ]] && echo 16 || echo 32)
prune=$([[ "$LOW_SPEC" == "1" ]] && echo 5500 || echo 10000)
EOF
    fi

    if ! grep -q '^\[qbtctestnet\]' "$CONF"; then
        cat >> "$CONF" <<EOF

[qbtctestnet]
server=1
listen=1
discover=1
dnsseed=1
fallbackfee=0.0001
logtimestamps=1
EOF
    fi

    append_if_missing "seednode=46.62.156.169:28333"
    append_if_missing "seednode=37.27.47.236:28333"
    append_if_missing "seednode=89.167.109.241:28333"
    append_if_missing "addnode=46.62.156.169:28333"
    append_if_missing "addnode=37.27.47.236:28333"
    append_if_missing "addnode=89.167.109.241:28333"
}

cli() {
    "$CLI" "${CLI_ARGS[@]}" "$@"
}

cmd_repair_peers() {
    if ! cli getblockchaininfo >/dev/null 2>&1; then
        echo "Node is NOT running."
        exit 1
    fi

    local count
    count=$(cli getconnectioncount 2>/dev/null || echo 0)
    if [[ "$count" -ge 2 ]]; then
        echo "Peer count healthy: $count"
        return
    fi

    for peer in "${BOOTSTRAP_PEERS[@]}"; do
        cli addnode "$peer" add >/dev/null 2>&1 || cli addnode "$peer" onetry >/dev/null 2>&1 || true
    done
    if [[ -n "$SEEDNODE" ]]; then
        cli addnode "$SEEDNODE" add >/dev/null 2>&1 || cli addnode "$SEEDNODE" onetry >/dev/null 2>&1 || true
    fi
    sleep 3
    count=$(cli getconnectioncount 2>/dev/null || echo 0)
    echo "Peer repair attempted. Connected peers: $count"
}

cmd_doctor() {
    if ! cli getblockchaininfo >/dev/null 2>&1; then
        echo "Node is NOT running (or RPC not reachable)."
        exit 1
    fi
    cmd_status
    local peers
    peers=$(cli getconnectioncount 2>/dev/null || echo 0)
    if [[ "$peers" -lt 2 ]]; then
        echo "Warning: low peer count detected ($peers). Attempting peer repair..."
        cmd_repair_peers
    fi
}

cmd_start() {
    ensure_config

    echo "Starting QuantumBTC testnet node..."
    echo "  Chain:    $CHAIN"
    echo "  Port:     28333 (P2P), 28332 (RPC)"
    echo "  Bech32:   qbtct1..."
    echo "  DAG:      GHOSTDAG K=32, 10s targets"
    echo "  DAA:      load-aware hardening enabled"
    echo "  PQC:      hybrid signing, Falcon default"
    echo "  Profile:  $([[ "$LOW_SPEC" == "1" ]] && echo 'low-spec' || echo 'standard')"
    echo ""

    if cli getblockchaininfo >/dev/null 2>&1; then
        echo "Node is already running."
        cmd_doctor
        return
    fi

    local extra_args=("$@")
    "$BITCOIND" "${DAEMON_ARGS[@]}" "${extra_args[@]}" \
        -fallbackfee=0.0001 \
        -server=1 \
        -listen=1 \
        -discover=1 \
        -dnsseed=1 \
        -logtimestamps=1 \
        -printtoconsole=0

    for _ in $(seq 1 30); do
        if cli getblockchaininfo >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done

    if ! cli getblockchaininfo >/dev/null 2>&1; then
        echo "Node failed to start or RPC is not reachable yet."
        exit 1
    fi

    cmd_repair_peers
    echo "Node started. Use '$0 status' to check."
    echo "Logs: ${DATADIR}/qbtctestnet/debug.log"
}

cmd_stop() {
    echo "Stopping QuantumBTC testnet node..."
    cli stop
    echo "Shutdown signal sent."
}

cmd_status() {
    if ! cli getblockchaininfo >/dev/null 2>&1; then
        echo "Node is NOT running (or RPC not reachable)."
        exit 1
    fi
    cli getblockchaininfo | python3 -c "
import sys, json
d = json.load(sys.stdin)
print('QuantumBTC Testnet Status')
print('=' * 40)
print(f'  Chain:        {d[\"chain\"]}')
print(f'  Blocks:       {d[\"blocks\"]}')
print(f'  Headers:      {d[\"headers\"]}')
print(f'  DAG mode:     {d.get(\"dagmode\", \"N/A\")}')
print(f'  DAG tips:     {d.get(\"dag_tips\", \"N/A\")}')
print(f'  GHOSTDAG K:   {d.get(\"ghostdag_k\", \"N/A\")}')
print(f'  PQC:          {d.get(\"pqc\", \"N/A\")}')
print(f'  Difficulty:   {d[\"difficulty\"]}')
print(f'  Pruned:       {d[\"pruned\"]}')
print(f'  Size on disk: {d[\"size_on_disk\"] / 1024 / 1024:.1f} MB')
"
}

cmd_info() {
    cli getblockchaininfo
}

cmd_peers() {
    if ! cli getpeerinfo >/dev/null 2>&1; then
        echo "Node is NOT running."
        exit 1
    fi
    local count
    count=$(cli getconnectioncount)
    echo "Connected peers: $count"
    if [[ "$count" -gt 0 ]]; then
        cli getpeerinfo | python3 -c "
import sys, json
peers = json.load(sys.stdin)
for p in peers:
    print(f'  {p[\"addr\"]:30s}  {p[\"subver\"]:30s}  height={p.get(\"synced_headers\", \"?\")}')
"
    fi
}

cmd_wallet() {
    if cli -rpcwallet="$WALLET" getwalletinfo >/dev/null 2>&1; then
        echo "Wallet '$WALLET' already loaded."
    elif cli loadwallet "$WALLET" >/dev/null 2>&1; then
        echo "Wallet '$WALLET' loaded."
    elif cli createwallet "$WALLET" >/dev/null 2>&1; then
        echo "Wallet '$WALLET' created."
    else
        echo "ERROR: Failed to create/load wallet '$WALLET'."
        exit 1
    fi
    cli -rpcwallet="$WALLET" getwalletinfo | python3 -c "
import sys, json
w = json.load(sys.stdin)
print(f'  Name:    {w[\"walletname\"]}')
print(f'  Balance: {w[\"balance\"]} QBTC')
print(f'  TxCount: {w[\"txcount\"]}')
"
}

cmd_address() {
    cmd_wallet >/dev/null 2>&1 || true
    local addr
    addr=$(cli -rpcwallet="$WALLET" getnewaddress "" "bech32")
    echo "$addr"
}

cmd_mine() {
    local count="${1:-1}"
    cmd_wallet >/dev/null 2>&1 || true
    local addr
    addr=$(cli -rpcwallet="$WALLET" getnewaddress "" "bech32")
    echo "Mining $count block(s) to $addr ..."
    for i in $(seq 1 "$count"); do
        local result hash height
        result=$(cli -rpcwallet="$WALLET" generatetoaddress 1 "$addr")
        hash=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin)[0][:16])" 2>/dev/null)
        height=$(cli getblockcount)
        echo "  [$i/$count] height=$height  hash=${hash}..."
    done
    echo ""
    cmd_status
}

cmd_send() {
    local to_addr="$1"
    local amount="$2"
    if [[ -z "$to_addr" || -z "$amount" ]]; then
        echo "Usage: $0 send <address> <amount>"
        exit 1
    fi
    cmd_wallet >/dev/null 2>&1 || true
    local txid
    txid=$(cli -rpcwallet="$WALLET" sendtoaddress "$to_addr" "$amount")
    echo "Sent $amount QBTC to $to_addr"
    echo "TxID: $txid"
}

cmd_sweep() {
    local to_addr="${1:-}"
    local keep="${2:-$SWEEP_KEEP_DEFAULT}"
    local max_send="${3:-$SWEEP_MAX_DEFAULT}"
    if [[ -z "$to_addr" ]]; then
        echo "Usage: $0 sweep <address> [keep_amount] [max_per_sweep]"
        exit 1
    fi
    cmd_wallet >/dev/null 2>&1 || true
    local balance
    balance=$(cli -rpcwallet="$WALLET" getbalance 2>/dev/null || echo 0)
    local send_amount
    send_amount=$(python3 - <<PY
from decimal import Decimal
bal = Decimal("$balance")
keep = Decimal("$keep")
cap = Decimal("$max_send")
amt = bal - keep
if amt <= Decimal("0.00001000"):
    print("0")
else:
    print(f"{min(amt, cap):.8f}")
PY
)
    if [[ "$send_amount" == "0" ]]; then
        echo "Nothing to sweep. Balance=$balance QBTC, keep=$keep QBTC"
        return 0
    fi
    local txid
    txid=$(cli -rpcwallet="$WALLET" sendtoaddress "$to_addr" "$send_amount")
    echo "Swept $send_amount QBTC to $to_addr"
    echo "TxID: $txid"
}

cmd_autosweep() {
    local to_addr="${1:-}"
    local every_mins="${2:-30}"
    local keep="${3:-$SWEEP_KEEP_DEFAULT}"
    local max_send="${4:-$SWEEP_MAX_DEFAULT}"
    if [[ -z "$to_addr" ]]; then
        echo "Usage: $0 autosweep <address> [interval_minutes] [keep_amount] [max_per_sweep]"
        exit 1
    fi
    ensure_datadir
    local sweep_script="$DATADIR/qbtc-autosweep.sh"
    cat > "$sweep_script" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export QBTC_DATADIR=$(printf '%q' "$DATADIR")
export QBTC_BINDIR=$(printf '%q' "$BINDIR")
export QBTC_WALLET=$(printf '%q' "$WALLET")
export QBTC_CONF=$(printf '%q' "$CONF")
exec $(printf '%q' "$SCRIPT_DIR/qbtc-testnet.sh") sweep $(printf '%q' "$to_addr") $(printf '%q' "$keep") $(printf '%q' "$max_send")
EOF
    chmod +x "$sweep_script"

    local cron_line="*/${every_mins} * * * * $sweep_script >> $DATADIR/qbtc-autosweep.log 2>&1"
    (crontab -l 2>/dev/null | grep -Fv "$sweep_script"; echo "$cron_line") | crontab -
    echo "Auto-sweep installed."
    echo "  Address:  $to_addr"
    echo "  Interval: every $every_mins minute(s)"
    echo "  Keep:     $keep QBTC"
    echo "  Max/send: $max_send QBTC"
    echo "  Log:      $DATADIR/qbtc-autosweep.log"
}

cmd_throttle() {
    local pct="${1:-$CPU_LIMIT_DEFAULT}"
    if ! [[ "$pct" =~ ^[0-9]+$ ]] || [[ "$pct" -lt 5 || "$pct" -gt 95 ]]; then
        echo "Usage: $0 throttle [cpu_percent_between_5_and_95]"
        exit 1
    fi
    local pid
    pid=$(pgrep -f "$BITCOIND" | head -1 || true)
    if [[ -z "$pid" ]]; then
        echo "bitcoind is not running. Start the node first."
        exit 1
    fi

    renice +10 -p "$pid" >/dev/null 2>&1 || true
    ionice -c3 -p "$pid" >/dev/null 2>&1 || true

    if command -v cpulimit >/dev/null 2>&1; then
        pkill -f "cpulimit.*-p ${pid}" >/dev/null 2>&1 || true
        local cores limit
        cores=$(nproc 2>/dev/null || echo 1)
        limit=$((pct * cores))
        cpulimit -p "$pid" -l "$limit" -b >/dev/null 2>&1 || true
        echo "Applied CPU cap: ${pct}% total on pid $pid (cpulimit -l $limit)"
    else
        echo "cpulimit not installed; applied nice/ionice only to pid $pid"
    fi
}

cmd_cli() {
    cli "$@"
}

usage() {
    echo "Usage: $0 <command> [args...]"
    echo ""
    echo "Commands:"
    echo "  start [bitcoind-args]   Start testnet node in background"
    echo "  stop                    Graceful shutdown"
    echo "  status                  Show chain and DAG status"
    echo "  info                    Raw getblockchaininfo JSON"
    echo "  peers                   Show connected peers"
    echo "  wallet                  Create or load miner wallet"
    echo "  address                 Get a new testnet address"
    echo "  mine [N]               Mine N blocks (default: 1)"
    echo "  send <addr> <amount>   Send QBTC"
    echo "  sweep <addr> [keep]    Drain wallet above a reserve balance"
    echo "  autosweep <addr> [minutes] [keep]  Install periodic wallet drain"
    echo "  throttle [pct]         Lower runtime CPU usage for bitcoind"
    echo "  repair-peers           Re-add bootstrap peers if connectivity is weak"
    echo "  doctor                 Show health and try to repair low peer count"
    echo "  cli [args...]          Pass-through to bitcoin-cli"
    echo ""
    echo "Environment:"
    echo "  QBTC_DATADIR   Custom data directory (default: ~/.bitcoin)"
    echo "  QBTC_BINDIR    Binary directory (default: ./src)"
    echo "  QBTC_WALLET    Wallet name (default: miner)"
    echo "  QBTC_SEEDNODE  Extra seed node to bootstrap from (ip:port)"
    echo "  QBTC_LOW_SPEC  Set to 1 for older or low-memory machines"
    echo "  QBTC_CPU_LIMIT Default CPU cap for throttle (default: 30)"
    echo "  QBTC_SWEEP_KEEP Reserve amount to keep during sweep (default: 1.0)"
    echo "  QBTC_SWEEP_MAX Max amount per sweep pass (default: 50)"
}

COMMAND="${1:-}"
shift || true

case "$COMMAND" in
    start)   cmd_start "$@" ;;
    stop)    cmd_stop ;;
    status)  cmd_status ;;
    info)    cmd_info ;;
    peers)         cmd_peers ;;
    wallet)        cmd_wallet ;;
    address)       cmd_address ;;
    mine)          cmd_mine "$@" ;;
    send)          cmd_send "$@" ;;
    sweep)         cmd_sweep "$@" ;;
    autosweep)     cmd_autosweep "$@" ;;
    throttle)      cmd_throttle "$@" ;;
    repair-peers)  cmd_repair_peers ;;
    doctor)        cmd_doctor ;;
    cli)           cmd_cli "$@" ;;
    help|-h|--help|"")
        usage ;;
    *)
        echo "Unknown command: $COMMAND"
        usage
        exit 1 ;;
esac
